format:
  html: {toc: true, toc-depth: 3, theme: cosmo, number-sections: false}
  revealjs: {theme: cosmo, navigation-mode: vertical, transition: slide, background-transition: fade, incremental: true}
project: {type: book}
book:
  chapters: [index.qmd, assignments.hw1.utils.qmd, assignments.hw1.q1.qmd, assignments.hw1.q2.qmd, assignments.hw1.q3_5.qmd, assignments.hw1.q6_9.qmd]
  title: Homework 1
