
---
format:
  html: {toc: true, toc-depth: 3, theme: cosmo, number-sections: false, output-file: assignments.hw1.q1.html}
fontsize: 0.9em
code-block-background: true
include-in-header: {text: '<link rel = "icon" href = "data:," />'}
toc-title-numbers: false
number-depth: 0

---
<style></style><style>.printedClojure .sourceCode {
  background-color: transparent;
  border-style: none;
}
</style><style>.clay-limit-image-width .clay-image {max-width: 100%}
.clay-side-by-side .sourceCode {margin: 0}
.clay-side-by-side {margin: 1em 0}
</style>
<script src="assignments.hw1.q1_files/md-default2.js" type="text/javascript"></script><script src="assignments.hw1.q1_files/md-default3.js" type="text/javascript"></script><script src="assignments.hw1.q1_files/katex4.js" type="text/javascript"></script><script src="assignments.hw1.q1_files/vega5.js" type="text/javascript"></script><script src="assignments.hw1.q1_files/vega6.js" type="text/javascript"></script><script src="assignments.hw1.q1_files/vega7.js" type="text/javascript"></script><link href="https://cdn.jsdelivr.net/npm/katex@0.16.10/dist/katex.min.css" rel="stylesheet" type="text/css" />

::: {.sourceClojure}
```clojure
(ns assignments.hw1.q1
  (:require
   [assignments.hw1.utils :refer :all]
   [fastmath.core :as m]
   [fastmath.random :as rand]
   [fastmath.stats :as s]
   [scicloj.hanamicloth.v1.api :as haclo]
   [tablecloth.api :as tc]))
```
:::


## Question 1
---

#### *1) Medical reports have shown that approximately 80% of North American smokers died of lung cancer. Among four smokers who recently died in Huron, Ohio,*

***a) what is the chance that exactly 2 of them are due to lung cancer?***

The `ncr` function calculates the number of combinations (n choose k):



$$C_n^k = \frac{n!}{k!(n-k)!}$$

This is used in the binomial probability distribution formula.

The `pdf-binomial` function calculates the probability mass function for a binomial distribution:

$$P(X = k) = \binom{n}{k} p^k (1-p)^{n-k}$$

Where:
        - $n$ is the number of trials
        - $k$ is the number of successes
        - $p$ is the probability of success on each trial

We can visualize the `n` and `p` specified Binomial Distribution with the following function:


::: {.sourceClojure}
```clojure
(comment
  (defn bin-cmf-viz
    "Creates a visualization of the binomial cumulative distribution function.
     n: number of trials
     p: probability of success on each trial"
    [n p]
    (let [data (tc/dataset
                {:k           (mapv str (range (inc n)))
                 :probability (map #(pmf-binomial % n p) (range (inc n)))
                 :cumulative  (reductions + (map #(pmf-binomial % n p) (range (inc n))))})]
      (-> data
          (haclo/layer-bar
           {:=x :k
            :=y :probability})))))
```
:::



::: {.sourceClojure}
```clojure
(bin-cmf-viz 4 0.8)
```
:::



```{=html}
<div><script>vegaEmbed(document.currentScript.parentElement, {"encoding":{"x":{"field":"x","type":"nominal"},"y":{"field":"y","type":"nominal"}},"usermeta":{"embedOptions":{"renderer":"svg"}},"width":400,"background":"floralwhite","layer":[{"mark":{"type":"bar","tooltip":true},"encoding":{"x":{"field":"k","type":"nominal"},"y":{"field":"probability","type":"quantitative"}},"data":{"values":"k,probability,cumulative\n0,0.0015999999999999986,0.0015999999999999986\n1,0.025599999999999984,0.02719999999999998\n2,0.15359999999999996,0.18079999999999993\n3,0.4096,0.5903999999999999\n4,0.4096000000000001,1.0\n","format":{"type":"csv"}}}],"height":300,"data":{"url":"assignments.hw1.q1_files\/0.csv","format":{"type":"csv"}}});</script></div>
```


Either observing the `probability` at `k=2`, above, or calculating it with the `pdf-binomial` function:


::: {.sourceClojure}
```clojure
(let [p 0.8 n 4 k 2
      probability (pmf-binomial k n p)]
  (answer
   (str
    "Probability of exactly " k " out of " n " smokers dying from lung cancer: "
    (* 100 (m/approx probability 4)) "%")))
```
:::


> <span style="color: black; font-size: 1.5em;">**Probability of exactly 2 out of 4 smokers dying from lung cancer: 15.36%**</span>

This can be done on the Calculator Casio fx-9750GII by doing the following steps:_unnamed [5 3]:

| :step | :button |                     :description |
|------:|---------|----------------------------------|
|     1 |  `MENU` |                   Open main menu |
|     2 |     `2` |                      Select STAT |
|     3 |    `F5` |                   Open DIST menu |
|     4 |    `F5` |           Select BINM (Binomial) |
|     5 |    `F1` | Choose bpd (probability density) |


***b) What is the chance that at least 3 of them are due to lung cancer?***

Notice that the probability of at least 3 is 1 minus the probability of less than 3 (at most 2). The `pdf-binomial` function calculates the probability mass function for a binomial distribution:

$$P(X \geq k) = 1 - P(X < k) = 1 - (P(X = 0) + P(X = 1) + ... + P(X = k-1))$$

$$= \sum_{i=0}^{k-1} P(X = i)$$


::: {.sourceClojure}
```clojure
(let [p 0.8 n 4 k 3
      prob (cmf-binomial (dec k) n p)
      probability (- 1 prob)]
  (answer
   (str
    "Probability of at least " k " out of " n " smokers dying from lung cancer: "
    (* 100 (m/approx probability 4)) "%")))
```
:::


> <span style="color: black; font-size: 1.5em;">**Probability of at least 3 out of 4 smokers dying from lung cancer: 81.92%**</span>

***c) What is the chance that at most 3 of them died of lung cancer?***


::: {.sourceClojure}
```clojure
(let [p 0.8 n 4 k 3
      prob (cmf-binomial k n p)
      pdf (pmf-binomial (inc k) n p)
      probability (- 1 pdf)]
  (answer
   (str
    "Probability of at most " k " out of " n " smokers dying from lung cancer: "
    (* 100 (m/approx prob)) "%")))
```
:::


> <span style="color: black; font-size: 1.5em;">**Probability of at most 3 out of 4 smokers dying from lung cancer: 59.0%**</span>

***d) Interpret the expected value and standard deviation of the number of lung cancer patients among the four smokers who recently died in Huron, Ohio.***

We can visualize the expected value of the number of lung cancer patients among the four smokers who recently died in Huron, Ohio by sampling the binomial distribution:


::: {.sourceClojure}
```clojure
(comment
  (defn binomial-dist-viz [sample-size n p]
    (let [binomial-dist (rand/distribution :binomial {:p p :trials n})
          samples (repeatedly sample-size #(rand/sample binomial-dist))
          data (-> (tc/dataset {:value samples})
                   (tc/group-by :value)
                   (tc/aggregate {:count tc/row-count})
                   (tc/add-column :with-cancer #(map str (:$group-name %))))
          plot (-> data
                   (haclo/layer-bar
                    {:=x :with-cancer
                     :=y :count}))
          mean-value (s/mean samples)]
      [plot (md (str "Mean of samples: " (m/approx mean-value 4)))])))
```
:::



::: {.sourceClojure}
```clojure
(binomial-dist-viz 1000 4 0.8)
```
:::



```{=html}
<div><p>[</p><div class="clay-sequential" style="margin-left:10%;width:110%;"><div><script>vegaEmbed(document.currentScript.parentElement, {"encoding":{"x":{"field":"x","type":"nominal"},"y":{"field":"y","type":"nominal"}},"usermeta":{"embedOptions":{"renderer":"svg"}},"width":400,"background":"floralwhite","layer":[{"mark":{"type":"bar","tooltip":true},"encoding":{"x":{"field":"with-cancer","type":"nominal"},"y":{"field":"count","type":"quantitative"}},"data":{"values":"$group-name,count,with-cancer\n3,411,3\n4,428,4\n2,132,2\n1,26,1\n0,3,0\n","format":{"type":"csv"}}}],"height":300,"data":{"url":"assignments.hw1.q1_files\/1.csv","format":{"type":"csv"}}});</script></div><div><p>Mean of samples: 3.235</p></div></div><p>]</p></div>
```


Looking at the many sampled Binomial distributions, we see most of the time the number of lung cancer patients is around 3. This is the expected value, shown below, with its theoretical expected value and standard deviation calculated with the following formulas:

$$E(X) = n * p$$


::: {.sourceClojure}
```clojure
(defn expected-value [n p]
  (* n p))
```
:::


$$SD(X) = \sqrt{(n * p * (1 - p))}$$


::: {.sourceClojure}
```clojure
(defn standard-deviation [n p]
  (Math/sqrt (* n p (- 1 p))))
```
:::



::: {.sourceClojure}
```clojure
(let [n 4
      p 0.8
      expected-value (expected-value n p)
      standard-deviation (standard-deviation n p)]
  (answer
   (str
    "Expected value: " expected-value ";   Standard deviation: " (m/approx standard-deviation))))
```
:::


> <span style="color: black; font-size: 1.5em;">**Expected value: 3.2;   Standard deviation: 0.8**</span>


```{=html}
<div style="background-color:grey;height:2px;width:100%;"></div>
```



```{=html}
<div><pre><small><small>source: <a href="https://github.com/adabwana/f24-m6410-hw1/blob/main/src/assignments/hw1/q1.clj">src/assignments/hw1/q1.clj</a></small></small></pre></div>
```
